# 哨兵服务端口
port 26379
protected-mode no

# 监控主节点，格式: sentinel monitor <主节点别名> <IP/域名> <端口> <客观下线所需哨兵同意数>
# 生产环境 3 个哨兵，法定人数（Quorum）设为 2
sentinel monitor micro_device_master 127.0.0.1  6379 2

# 哨兵连接主从节点时使用的密码
sentinel auth-pass micro_device_master 123456

# 主节点失效判定的超时时间（3秒无响应视为异常）
sentinel down-after-milliseconds micro_device_master 3000

# 故障转移超时时间（3分钟）
sentinel failover-timeout micro_device_master 180000

# 故障转移时，允许同时同步新主节点的从节点数量
sentinel parallel-syncs micro_device_master 1