# -------------------------------------------------------------------
# 1. 基础网络与安全配置
# -------------------------------------------------------------------
# 监听所有网络接口，允许容器外访问
bind 0.0.0.0
port 6379
# 关闭保护模式
protected-mode no

# 企业规范：必须设置复杂的访问密码
requirepass 123456

# -------------------------------------------------------------------
# 2. 持久化策略 (确保单机宕机后数据可恢复)
# -------------------------------------------------------------------
# 开启 RDB 快照机制（在指定时间内有指定次数的写操作则触发快照）
save 900 1
save 300 10
save 60 1