services:
  ##################### 微服务配置服务 #####################
  micro-consul:
    image: consul:${CONSUL_VERSION}
    container_name: micro-consul
    restart: always
    ports:
      - "${CONSUL_WEB_PORT}:8500"
      - "${CONSUL_DNS_PORT}:8600/tcp"
      - "${CONSUL_DNS_PORT}:8600/udp"
    volumes:
      - ${CONSUL_LOCAL_DIR}/data:/consul/data
      - ${CONSUL_LOCAL_DIR}/config:/consul/config
    command: "agent -server -bootstrap-expect=1 -client=0.0.0.0 -config-dir=/consul/config -data-dir=/consul/data"
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  ##################### 微服务配置服务 #####################
