services:
  ##################### 微服务配置服务 #####################
  micro-consul:
    image: consul:${CONSUL_VERSION}
    container_name: micro-consul
    restart: always
    ports:
      - "${CONSUL_WEB_PORT}:8500"
      - "${CONSUL_DNS_PORT}:8600/tcp"
      - "${CONSUL_DNS_PORT}:8600/udp"
    volumes:
      - ${CONSUL_LOCAL_DIR}/data:/consul/data
      - ${CONSUL_LOCAL_DIR}/config:/consul/config
    command: "agent -server -bootstrap-expect=1 -client=0.0.0.0 -config-dir=/consul/config -data-dir=/consul/data"
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  ##################### 微服务数据服务 #####################
  micro-sqldb:
    image: ${SQLDB_TYPE}:${SQLDB_VERSION}
    container_name: micro-sqldb
    restart: always
    volumes:
      - micro-sqldb-data:/var/lib/postgresql/data
      - ./docker/sql/db.init.sql:/docker-entrypoint-initdb.d/init-multi-db.sql
    environment:
      POSTGRES_USER: ${SQLDB_USER}
      POSTGRES_PASSWORD: ${SQLDB_PASSWORD}
      ## 默认: 随便填
      POSTGRES_DB: ${SQLDB_DEF_DB}
    ports:
      - "${SQLDB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQLDB_USER} -d ${SQLDB_DEF_DB}"]
      retries: ${SQLDB_RETRIES}
      timeout: ${SQLDB_TIMEOUT}
      interval: ${SQLDB_INTERVAL}

  ##################### 微服务配置服务 #####################

volumes:
  micro-sqldb-data:
